### ISSUE TITLE
Réévaluer les permissions de l'application

### ISSUE THREAD

**Issue by HorlogeSkynet** [ApplETS/ETSMobile-Android2#102]
Hello,

Pour commencer : l'application a l'air vraiment cool, et le fait que les sources soient dispo' ajoute une plus-value inéstimable... et la possibilité de créer des _issues_ de ce genre 😜

Requête : Pourquoi nécessite-t-elle d'avoir accès à la géo-localisation ?
J'ai parcouru un peu ce qu'elle propose, et en ai conclu que les accès aux contacts, au calendrier, au stockage et au téléphone pourraient effectivement servir, mais pas la localisation.
Est-ce que je me trompe, ou bien est-elle vraiment inutile et devrait-être retirée ?

Merci !

**Comment by ttauveron** [comment]
Salut,

Je crois que cette permission servait pour l'onglet sécurité quand une Google map était utilisée, ce n'est probablement plus nécessaire effectivement.

Merci d'avoir créé le issue, c'est vrai que c'est une belle valeur ajoutée pour le projet d'avoir des contributions ouvertes de ce genre!

**Comment by HorlogeSkynet** [comment]
Parfait, merci pour la réponse rapide !

**Comment by zaclimon** [comment]
Les accès pour la localisation ont été retirées, le tout devrait être actif à la prochaine version.
