### ISSUE TITLE
Crash à l'ouverture d'un lien dans les évènements

### ISSUE THREAD

**Issue by ttauveron** [ApplETS/ETSMobile-Android2#105]
Aussi les évènements déjà passés semblent s'afficher quand même.

**Comment by ttauveron** [comment]
![image](https://user-images.githubusercontent.com/1558361/30398855-e5574eee-989f-11e7-89c6-e78b01e0ab89.png)
![image](https://user-images.githubusercontent.com/1558361/30398862-ecb59b6e-989f-11e7-917b-276e964a9518.png)

**Comment by ttauveron** [comment]
An issue in EvenementCommunauteAdapter.java line 119 has occurred in ÉTSMobile Android: https://fabric.io/applets/android/apps/ca.etsmtl.applets.etsmobile/issues/59b99192be077a4dcc941d66

**Comment by zaclimon** [comment]
La fonctionnalité d'événements a été retirée de l'application. Cette situation n'est donc plus valable.
