### ISSUE TITLE
Changements dans l'API cooptel pour la bande passante des résidences

### ISSUE THREAD

**Issue by ttauveron** [ApplETS/ETSMobile-Android2#106]
Cooptel a changé son API pour voir la consommation d'internet aux résidences étudiantes.
Désormais, on entre sa chambre pour connaitre sa consommation personnelle, l'internet ne semble plus être partagé pour tout l'appartement.

Finalement, l'affichage de l'internet restant dans ETSMobile pourrait se résumer à une progress bar comme celle-ci : 
![image](https://user-images.githubusercontent.com/1558361/30399589-2bb77bbe-98a2-11e7-94fa-b2e375210641.png)

Une proposition serait de retirer l'onglet "bande passante" et proposer à l'utilisateur de rentrer sa phase,appartement et numéro de chambre dans les préférences puis afficher la consommation dans la page Today.

Sinon, simplement ajouter un champs pour sélectionner chambre A,B,C ou D dans la page "Bande passante" et garder le fonctionnement comme avant (après mise à jour de l'API)

Voilà la nouvelle URL à utiliser dans l'application : https://api3.clubapplets.ca/cooptel?phase=1&appt=206&chambre=a

**Comment by HorlogeSkynet** [comment]
J'opterais pour la seconde proposition !

Les identifiants deviennent :
* ets-res{PHASE}-{APPART}-{CHAMBRE}
* ets{APPART}

Ici c'est mis à jour et ça marche : https://gist.github.com/HorlogeSkynet/be9589cfe7e3734d5420aa28d5c6201c

👋

**Comment by ttauveron** [comment]
Merci @HorlogeSkynet !
Le changement est déjà présent dans l'API mais pas encore en production : https://github.com/ApplETS/applets-java-api/commit/fcb6e113ddebbb66585cf46180afc5e3b7bc83c8
En effet, la deuxième proposition est certainement la plus simple à implémenter et pourrait être réalisée rapidement.

**Comment by HorlogeSkynet** [comment]
C'est bien ce que j'avais cru comprendre, pour la phase 3 cela va être plus compliqué :

![screenshot from 2017-09-21 11-20-30](https://user-images.githubusercontent.com/5331869/30703888-f6151fac-9ebe-11e7-9999-0f677b7e1d83.png)

**Comment by ttauveron** [comment]
La mise à jour de l'API est finalement en production :
https://api3.clubapplets.ca/cooptel?phase=1&appt=206&chambre=a

**Comment by zaclimon** [comment]
@Sonphil Est-ce que #113 règle le problème?

**Comment by Sonphil** [comment]
@zaclimon Oui, l'utilisateur peut entrer le numéro de la chambre, car, désormais, on utilise : https://api3.clubapplets.ca/cooptel?phase=1&appt=206&chambre=a

On affiche simplement un message pour les résidents de la phase 3.

**Comment by zaclimon** [comment]
Okk parfait alors! On peut fermer ça dans ce cas.
