### ISSUE TITLE
Redirection au browser à l'ouverture de Monets

### ISSUE THREAD

**Issue by jerrydark** [ApplETS/ETSMobile-Android2#110]
Au lieu de montrer portail dans l'app, il ouvre le lien portail.etsmtl.ca dans le browser.
One plus A3000

**Comment by zaclimon** [comment]
Oui nous utilisons en fait le Chrome Custom Tabs pour l'affichage de MonETS. Son comportement est d'utiliser le navigateur par défaut si Chrome ne l'est pas sur un appareil.

**Comment by jerrydark** [comment]
Ah ok. Apres quelque tests je vois que le chrome doit etre le navigateur par defaut pour que ça marche.
