### ISSUE TITLE
Corriger l'affichage du background dans la page Login

### ISSUE THREAD

**Issue by ttauveron** [ApplETS/ETSMobile-Android2#13]
Selon différentes résolutions, l'image peut être trop petite pour tenir dans tout l'écran.

**Comment by gnut3ll4** [comment]
Image plus haute qualité possible : http://en.etsmtl.ca/ETS/media/Prive/logo/ETS-pavA-B-11x5-300DPI.jpg

**Comment by komlan55** [comment]
Ok donc on met cette image dans le Login alors!

**Comment by mikefaille** [comment]
@gnut3ll4 Avec une image de 3.7 meg, tu viens d'augmenter substantiellement l'utilisation de la ram. Ça semble être un bon taux de compression pour une image 4k. Toutefois, ce ne sont pas tous les appareils mobiles qui peuvent afficher 4k. De plus, ceux qui ont besoin de plus de mémoire ce ne sont pas des appareils avec un écran 4k. Ce que je propose, c'est aussi de supporter les appareils d'entrés de gamme à 150$ (un achat responsable pour un étudiant). 

Ainsi, en adaptant la taille de l'image selon la résolution de l'écran de l'usager, les étudiants les moins fortunés seront en mesure d'utiliser ÉTS Mobile eux aussi ;-)

**Comment by gnut3ll4** [comment]
@mikefaille oui tu as raison, c'était pas très explicite mais je pensais mettre cette image à titre de référence pour pouvoir ensuite la modifier avec un logiciel de retouches et/ou l'intégrer dans l'app selon les bonnes pratiques!

**Comment by mikefaille** [comment]
J'en doute pas ! Ahaha, je voulais juste te taquiner.

**Comment by gnut3ll4** [comment]
Une lib qui peut être cool : https://github.com/flavioarfaria/KenBurnsView

**Comment by komlan55** [comment]
C'est nice, est ce qu'on a une image dans le genre pour l'ETS?

**Comment by gnut3ll4** [comment]
Peut être ... :stuck_out_tongue:
