### ISSUE TITLE
Problème de connexion au compte

### ISSUE THREAD

**Issue by khalfe** [ApplETS/ETSMobile-Android2#134]
Bonjour,
Je n'arrive plus à me connecter à l'application depuis que je l'ai réinstallée, message "Impossible de se connecter au serveur".

**Comment by zaclimon** [comment]
Salut! Désolé du retard pour une réponse. Bonne nouvelle, le problème a été réglé avec le numéro suivant #136. Le changement devrait être effectif dès la prochaine mise-à-jour de l'application.

**Comment by zaclimon** [comment]
La mise-à-jour a été mise en production. Par conséquent, ce problème est considéré résolu.
