### ISSUE TITLE
Ajouter un tri sur les cours dans Moodle

### ISSUE THREAD

**Issue by gnut3ll4** [ApplETS/ETSMobile-Android2#15]
Les cours s'affichent maintenant dans le mauvais ordre sur Moodle, il y a donc besoin d'un tri pour que l'ordre aille de la session la plus récente à la plus ancienne, quelque soit la réponse de l'API Moodle.

**Comment by sdetilly** [comment]
done! Tester sur mon cell et ça marche :) je vais pull request-er sous peu, je vais travailler sur un autre petit bug!
