### ISSUE TITLE
Ajouter un tri sur la page aujourd'hui

### ISSUE THREAD

**Issue by gnut3ll4** [ApplETS/ETSMobile-Android2#16]
Un cours modifié s'ajoute à la fin de la liste, même si c'est le premier cours qui a lieu.
Il faut ajouter un tri dans la page aujourd'hui pour que les cours s'affichent en ordre.

**Comment by martingemme** [comment]
By The Way, vous n'affichez qu'un cours pour la même période (dans aujourd'hui et l'horaire). Par exemple j'ai 2 lab en même temps (Lab A et B), sur Android vous n'avez qu'un des deux (soit le A, soit le B), alors que sur Windows Phone j'affiche les deux. Je pense éventuellement ajouter une page pour gérer ça, mais c'est quelque chose à penser

**Comment by sdetilly** [comment]
déjà fait| :)
