### ISSUE TITLE
Afficher tous les cours dans les notes

### ISSUE THREAD

**Issue by gnut3ll4** [ApplETS/ETSMobile-Android2#19]
Actuellement, seulement 5 cours s'affichent en ligne.
Il faut permettre d'afficher d'autres cours sur une ligne en dessous pour les utilisateurs qui ont plus que 5 cours.

**Comment by yvesmillette** [comment]
Fait par
https://github.com/komlan55/ETSMobile-Android2/commit/cf38b6aa44140fecf7b7fecc552608bcab4713a3

![321b3ef515cbcf6bb0403f114f09281b](https://cloud.githubusercontent.com/assets/13698360/13437473/727aa6ca-dfb2-11e5-97d7-20982700db83.png)
