### ISSUE TITLE
Ajouter un menu pour les paramètres de l'application

### ISSUE THREAD

**Issue by gnut3ll4** [ApplETS/ETSMobile-Android2#21]
Suite à de nombreux commentaires des utilisateurs qui trouvent contraignant le fait de lier la langue du téléphone à ÉTSMobile, il faudrait ajouter un menu «Paramètres» global à toute l'application (Comme «Déconnexion») qui permet de changer la langue de l'application.

**Comment by sdetilly** [comment]
J'ai créer un petit menu "langage" au dessus de "Déconnexion".
