### ISSUE TITLE
Intégrer MonÉTS dans le menu

### ISSUE THREAD

**Issue by gnut3ll4** [ApplETS/ETSMobile-Android2#23]
En attendant de meilleures intégrations, il serait appréciable d'ajouter un accès rapide à MonÉTS depuis ÉTSMobile dans une WebView.

Dans un premier temps, cela pourrait consister à ouvrir un navigateur sur l'url de MonÉTS sans WebView.
Dans un deuxième temps, nous pourrions utiliser CAS afin que l'utilisateur n'ait pas à entrer son mot de passe à chaque fois.

**Comment by sdetilly** [comment]
all done, voir pull-request #35
