### ISSUE TITLE
Ajouter un today widget

### ISSUE THREAD

**Issue by jjghali** [ApplETS/ETSMobile-Android2#36]
On devrait avoir un widget qui permet de voir les cours que l'on a aujourd'hui du même style qu'un calendrier.

**Comment by gnut3ll4** [comment]
@jjghali est-ce que l'export de l'horaire dans le calendrier + widget calendrier ferait l'affaire à la place?

**Comment by komlan55** [comment]
Est-ce que la tâche est complété?? SI oui, @Sonphil  crée un pull request

**Comment by Sonphil** [comment]
Il me reste juste à ajouter une image de preview et tester avec la branche dev.
![image](https://cloud.githubusercontent.com/assets/22182973/22859899/d6a7e328-f0ba-11e6-9174-3624f2597c04.png)

**Comment by komlan55** [comment]
Okok sounds good :+1: . Merge dev dans ta branch et non le contraire. C'est plus simple ainsi

**Comment by gnut3ll4** [comment]
Wow mega sexy comme widget, good job !!! T'as des cours le dimanche toi? :stuck_out_tongue: 

Peut être qu'on pourrait essayer de merger dans la branche pre-dev qui contient les modification de @komlan55 sur le UI?

**Comment by gnut3ll4** [comment]
@Sonphil Une astuce que j'utilise pour afficher des cours les jours où tu n'en as pas (quand tu es en stage par exemple) est de changer la date du téléphone via les paramètres. Par contre, ça peut perturber certains services qui utilisent le SSL, basé sur des certificats délimités dans le temps.

**Comment by Sonphil** [comment]
:smiley: Non, pas de cours le dimanche. J'avais juste mis une autre date pour la liste dans le but de tester. Merci pour l'astuce!
