### ISSUE TITLE
Remettre un calendar view dans Schedule

### ISSUE THREAD

**Issue by komlan55** [ApplETS/ETSMobile-Android2#37]
Ajouter un Calender view et modifier le Listview existant pour qu'il contienne seulement les cours de la journée choisi dans le calender view.

**Comment by komlan55** [comment]
Cela rendre le menu item Today inutile et le fragment concerné. Donc il faudrais les enlever quand terminer

**Comment by gnut3ll4** [comment]
Pour information, la vue "Today" est supposée contenir aussi les événements ÉTS -> #33

**Comment by gnut3ll4** [comment]
Good job ! 
Les événements ÉTS faits par Simon ont été intégrés aussi dans la CalendarView #45
