### ISSUE TITLE
Notification silencieuse une heure avant le cours

### ISSUE THREAD

**Issue by sdetilly** [ApplETS/ETSMobile-Android2#39]
L'idée est de créer une notification soit silencieuse (elle apparaît dans la notification bar sans faire vibrer/sonner le téléphone), soit configurable (le user décide) environ une heure avant le cours. La notification contiendrait l'information du local, heure-début, heure-fin et le nom du cours.

**Comment by gnut3ll4** [comment]
Si tu veux faire quelque chose de vraiment cool, ça serait implémenter l'API google calendar, créer un calendrier "Cours ÉTS" sur le google de l'utilisateur et synchroniser les cours ÉTS dedans directement. Éventuellement à plus long terme, une option pour ajouter un rappel d'événement google calendar.

Ça prendrait un service côté client qui s'exécute toutes les x heures et qui s'occupe de faire la synchronisation à la place du chargement de la vue.

Je travaille actuellement sur une fonctionnalité similaire, une pull request suivra.
