### ISSUE TITLE
Refactor: DefaultHttpClient

### ISSUE THREAD

**Issue by sdetilly** [ApplETS/ETSMobile-Android2#41]
Le problème est que notre code utilise, à plusieurs reprises, DefaultHttpClient pour communiquer avec nos API. Ceci est un problème car avec les nouvelles versions du Android SDK, cette librairie n'est plus supporté. Il serait donc préférable de changer tous les instances du DefaultHttpClient pour OkHttp. OkHttp est une librairie très populaire et facile à utiliser.

Pour un exemple sur l'utilisation de OkHttp, vous pouvez consulter BandwidthFragment.java :)

PS: Tu peux générer un code presque "tout-fait" sur Postman. Simplement entrer le URL dans Postman et clicker sur generate Code puis choisir Java > OkHttp.

**Comment by zaclimon** [comment]
Le changement a été fait depuis un certain moment mais étrangement le billet n'avait pas été fermé. Il est donc le moment de le changer adéquatement.
