### ISSUE TITLE
Retirer les binaires de l'historique git 

### ISSUE THREAD

**Issue by gnut3ll4** [ApplETS/ETSMobile-Android2#53]
Voir discussion : https://github.com/ApplETS/ETSMobile-Android2/commit/a51b89bfa0495583a21e0146270fc6e3f3bf4d5a#commitcomment-18891774

Utiliser l'outil : https://rtyley.github.io/bfg-repo-cleaner/

**Les contributeurs devront repartir de la branche nettoyée pour leurs modifications car bfg change les hash des commits, une fusion créerait donc un double de tous les commits dans l'historique.**

**Comment by mikefaille** [comment]
Voici les étapes à suivres : 
```
git clone --mirror https://github.com/ApplETS/ETSMobile-Android2.git
wget http://repo1.maven.org/maven2/com/madgag/bfg/1.12.13/bfg-1.12.13.jar -O <chemin vers bfg>/bfg.jar
java -jar <chemin vers bfg>/bfg-1.12.13.jar --delete-files "*\.{jar,class}"
git reflog expire --expire=now --all && git gc --prune=now --aggressive
```

Pour comprendre les commandes ci-dessus, voir https://rtyley.github.io/bfg-repo-cleaner/

**Comment by mikefaille** [comment]
Je vois qu'il reste encore pas mal d'autres types de fichier à gérer comme les dex. Je regarde ça.

**Comment by mikefaille** [comment]
Ok ! Pour la commande à utiliser (en référence à la commande ci-haut) : 
```
java -jar ~/apps/bfg-1.12.13.jar --delete-files "*\.{jar,class,dex,apk,jks},*app-debug*,bin,*.ear,.gradletasknamecache" --delete-folders "{build,out,bin,gen,.gradle,.idea}" .
```

**Comment by gnut3ll4** [comment]
Bien joué !!

**Comment by mikefaille** [comment]
Par contre, on ne peut pas faire de pull request pour ça puisque l'opération change l'historique. De plus, il faut tester les changements de manière s'assurer que ça fonctionne.

Pour tester, puisque le commit HEAD n'est pas touché par l'opération, il faut aller chercher l'avant dernier commit.

**Comment by gnut3ll4** [comment]
Merci encore @mikefaille le repo est nettement moins lourd !
