### ISSUE TITLE
Corriger le bug du lien téléphonique dans le bottin

### ISSUE THREAD

**Issue by yvesmillette** [ApplETS/ETSMobile-Android2#55]
Ceci est une suggestion intéressante de David Morgan.

Il serait pertinent de permettre d'initialiser un appel ou d'envoyer un courriel en interagissant respectivement avec le numéro de téléphone ou le courriel dans le bottin.

**Comment by gnut3ll4** [comment]
Sur Android c'est déjà le cas non?

**Comment by MarcantVez** [comment]
Oui c'est déjà là sur Android. Reste à voir pour iOS.

**Comment by yvesmillette** [comment]
Sur Android c'est le cas seulement pour le courriel.

**Comment by gnut3ll4** [comment]
Un bug sur certains téléphones, le lien pour composer automatiquement le numéro n'est pas activé.
![screenshot_2016-09-22-11-28-22](https://cloud.githubusercontent.com/assets/1558361/18754922/4787fa7e-80b8-11e6-892c-6457bcd862b3.png)

**Comment by zaclimon** [comment]
La capture ci-dessus fait allusion à quel téléphone?

**Comment by yvesmillette** [comment]
Samsung G870A Lollipop 5.0

**Comment by zaclimon** [comment]
Hmm il y a quelque chose de bizarre, le lien semble être fonctionnel dans l'appareil fautif après une reconfiguration de celui-ci.
![screenshot_2017-01-13-23-01-01](https://cloud.githubusercontent.com/assets/1891861/21951668/09acf05a-d9d8-11e6-9a46-a49206a74050.png)

**Comment by zaclimon** [comment]
Je vais fermer l'issue étant donné qu'elle semble être fixed et que le commit a été merged. Elle sera réouverte si la situation survient à nouveau.
