### ISSUE TITLE
Afficher une barre d'avancement de la session

### ISSUE THREAD

**Issue by gnut3ll4** [ApplETS/ETSMobile-Android2#57]
Dans la vue Today par exemple, du premier jour de la session au dernier jour des examens.

**Comment by Sonphil** [comment]
Cette affichage de la barre de progression convient-il?
![image](https://cloud.githubusercontent.com/assets/22182973/21874814/67299ede-d845-11e6-9bfc-7568442927a3.png)

**Comment by gnut3ll4** [comment]
:+1:
