### ISSUE TITLE
Fusionner TodayFragment et HoraireFragment

### ISSUE THREAD

**Issue by komlan55** [ApplETS/ETSMobile-Android2#60]
**Vue en liste** : les 2 ne doivent pas être dans la separé
- [ ] Horraire journée courante
- [ ]  Liste de cours suivant la journée courante jusqu'à la fin de la session

**Vue calendrier**
Laisser tel quel

**Comment by gnut3ll4** [comment]
Quel est le problème avec ces deux vues séparées?

**Comment by komlan55** [comment]
C'est plus logique quels soit fusionné étant donné quel donne un horaire

**Comment by gnut3ll4** [comment]
Ça serait un sujet à discuter selon moi. 
La vue Today est sensée être la vue d’accueil de l'application, l'idée étant d'avoir dans cette vue un aperçu des informations utiles pour la date d'aujourd'hui, tout en gardant la possibilité de rajouter des items (un peu comme Google Now).
De plus, le ticket est difficile à classer dans les catégories liées aux normes de maintenance : perfective (pas une nouvelle fonctionnalité), preventive (pas de problème latent à priori), adaptive (le système ne le requiert pas), et corrective (ce n'est pas un bug).
Que penses-tu de remettre ce issue à plus tard, après avoir réglé les problèmes ou les améliorations plus importants?

**Comment by komlan55** [comment]
Je suis d'accord avec le fait que le ticket soit dur a classer et que c'est loin d'être une priorité. Cependant, je ne vois toujours pas l'utilité d'avoir ces 2 vues séparé. Ce que ta dit par rapport au "Google now" empêche aucunement la fusion. Au besoin,on peut même donner la possibilité de  cacher la liste de cours lorsqu'on veut uniquement voir la vu du jour

**Comment by zaclimon** [comment]
Fermé car le développement de cette fonctionnalité n'aura probablement pas lieu sur cette version d'ÉTSMobile. Pour les plus récents développements, voir le lien ci-dessous:

https://github.com/ApplETS/Notre-Dame
