### ISSUE TITLE
Ajouter une option pour désactiver les notifications

### ISSUE THREAD

**Issue by aviau** [ApplETS/ETSMobile-Android2#66]
Salut!

J'aimerais pouvoir désactiver les notifications dans l'application Android.

**Comment by gnut3ll4** [comment]
Salut @aviau,

Tu peux désactiver les notifications d'une application dans les paramètres du téléphone, quelque chose comme : Settings, Apps, [Application de ton choix], Notifications, Block all

**Comment by aviau** [comment]
C'est un bon workaround, merci! Mais la fonctionnalité devrait quand même être présente directement dans l'application.

**Comment by gnut3ll4** [comment]
Est-ce que tu reçois beaucoup les notifications du portail?

**Comment by aviau** [comment]
Je reçoit des notifications de moodle à chaque fois que je termine un quizz, et ensuite de signets quand la note du quizz apparaît dans signets.

C'est particulièrement useless parce que je savais ma note au moment ou j'ai terminé le quizz, alors c'est 2 notifications inutiles.

En tout cas, le volume de notifications n'est pas nécessairement le problème, c'est plutôt que l'application s'est mise à me notifier sans même que je lui aie demandé et que je n'ai pas de manière de le désactiver.

Je suis certain qu'un bon nombre d'utilisateurs vont aimer les notifications, mais pas moi.

---

C'est un autre sujet, mais j'évite d'activer ce genre de fonctionnalités dans les applications de mon téléphone parce que c'est le genre de fonctionnalité qui vont contribuer à rendre mon téléphone encore plus addictif. C'est le genre de feature qui me donne une raison de plus de regarder mon téléphone pour voir si j'ai eu une notification.

Un article que j'ai bien aimé sur le sujet: [Des millions d’heures sont juste volées à la vie des gens]( http://tempsreel.nouvelobs.com/rue89/rue89-le-grand-entretien/20160604.RUE3072/tristan-harris-des-millions-d-heures-sont-juste-volees-a-la-vie-des-gens.html)

> Ce serait quoi un design « éthique », du coup ?

> Ce serait des technologies qui nous rendraient notre liberté de choix. **Si ton téléphone fonctionnait pour toi, il ne te dirait pas, comme aujourd’hui « voici tout ce que tu es en train de manquer** »


C'est un drôle de hasard parce que je suis justement tombé sur un vidéo qui parlais du sujet aujourd'hui: [The Millennial Question - Simon Sinek](https://www.youtube.com/watch?v=vudaAYx2IcE)

**Comment by gnut3ll4** [comment]
On dirait que les notifications ne fonctionnent pas avec tout le monde.

Il s'agit en fait des notifications du portail MonÉTS, tu devrais pouvoir choisir lesquelles tu veux recevoir en configurant ton feed sur le portail, c'est tout de même une belle valeur ajoutée d'être notifié en temps réel de la correction d'un examen ou de la côte obtenue dans un cours.

Je trouve l'autre sujet intéressant, merci de partager cette perspective et d'alimenter la réflexion collective. Heureusement, le système a un mécanisme de gestion des notifications built-in que tu as pu utiliser pour te libérer de cette fonctionnalité qui peut certainement devenir intempestive, on s'en sort pas si mal hein? :wink:

**Comment by mikefaille** [comment]
@gnut3ll4  Voici ma proposition : 
Si on vient de recevoir une notification de l'application, bloquer l'envoie d'une nouvelle notification. Peut-être aussi que le bouton permettant de réduire les notifications devrait être d'avantage mis de l'avant par accessibilité; non pas parce que l'on est pas capable d'aller le chercher. Le point c'est que les applications mobiles envoient tellement de notification que ça devient du bruit. Il n'y a pas seulement ETSmobile; il y en a plusieurs autres. Ainsi, en avoir trop, c'est comme crier au loup pour rien mais lorsqu'il y a vraiment de quoi d'intéressant/urgent on ne s'intéresse plus à notre cell pour ces notifications. Implying que 3 autres applications que ÉTS mobile peut en somme causer un désintérer des notification pour l'utilisateur final. Je crois ainsi que ça serait une bonne idée de réouvrir le bug pour voir ce qu'il est possible de faire.

**Comment by gnut3ll4** [comment]
Je pense que l'app est toujours ouverte aux options de personnalisation, tu es plus que le bienvenu à soumettre une pull request !

**Comment by mikefaille** [comment]
J'y verrai au cours du mois prochain mais je ne peux prendre d'engagement pour l'instant.
