### ISSUE TITLE
Amélioration de l'interface utilisateur ÉTSMobile Wearable

### ISSUE THREAD

**Issue by ttauveron** [ApplETS/ETSMobile-Android2#70]
Mon coloc a installé ÉTSMobile sur sa montre intelligente, j'ai pu voir de quoi ça avait l'air. 
Voici une proposition de changements sur l'interface utilisateur : 

![conception interface utilisateur etsmobile wearable](https://cloud.githubusercontent.com/assets/1558361/22817522/c8ab3e36-ef35-11e6-990a-1ee85115b78a.jpg)

Les contours rouges sont un Progress qui commence gris au début du cours et devient entièrement rouge à la fin.

**Comment by komlan55** [comment]
C'est vraiment bien comme design!

**Comment by yvesmillette** [comment]
Dis à William de rejoindre le club! 👍
