### ISSUE TITLE
Corriger le problème d'affichage tronqué dans la vue Moodle

### ISSUE THREAD

**Issue by gnut3ll4** [ApplETS/ETSMobile-Android2#8]
Voir https://github.com/grantland/android-autofittextview
Déjà intégré pour le détail des notes : 

Layout : https://github.com/ApplETS/ETSMobile-Android2/blob/c0e1744d41ffc628a1db910c7f670936b86baf79/app/src/main/res/layout/notes_details_fragment.xml#L15

Code : https://github.com/ApplETS/ETSMobile-Android2/blob/dev/app/src/main/java/ca/etsmtl/applets/etsmobile/ui/fragment/NotesDetailsFragment.java#L92

**Comment by sdetilly** [comment]
Done! photo envoyé sur slack dans #android
