### ISSUE TITLE
Chargement infructueux des portlets dans MonETS

### ISSUE THREAD

**Issue by ttauveron** [ApplETS/ETSMobile-Android2#83]
Lorsque l'on ouvre l'onglet MonETS, les portlets chargent à l'infini sans afficher l'information.
Il est possible que cela soit un problème d'AJAX à l'intérieur d'une webview.
Peut être que le problème pourrait se régler en changeant la configuration de la webview.
Une solution pourrait aussi être d'ouvrir MonETS dans le navigateur à la place de l'afficher dans une webview.

![image](https://cloud.githubusercontent.com/assets/1558361/26537426/6e566956-440d-11e7-89b7-dff95de42e93.png)

**Comment by ttauveron** [comment]
- Survient sur Galaxy S7, HTC One M8
- Ne survient pas sur ONEPLUS A3000

**Comment by zaclimon** [comment]
Survient aussi sur Pixel (Android 7.1.1)

**Comment by Hamtara** [comment]
Les portlets "Calendrier" et "Cours" ne semblent pas affectés par le temps de chargement infini.

**Comment by zaclimon** [comment]
La situation a été réglée avec le PR 90 qui vient juste d'être "merged" Si besoin, elle sera rouverte.
