### ISSUE TITLE
Ajouter une vue "Moodle Assignments"

### ISSUE THREAD

**Issue by ttauveron** [ApplETS/ETSMobile-Android2#88]
Les Moodle Assignments sont les travaux à rendre sur la plateforme Moodle.

Il existe un endpoint dans l'API Moodle qui permet d'obtenir ces Assignments contenant les dates de remise.

https://ena.etsmtl.ca/webservice/rest/server.php?moodlewsrestformat=json&wstoken=(TOKEN)&wsfunction=mod_assign_get_assignments&courseids[]=(COURSE_ID)

Il serait potentiellement intéressant d'avoir une vue dans l'application pour consulter les travaux à rendre et éviter les rendus en retard.

**Comment by zaclimon** [comment]
Lié à #114

**Comment by zaclimon** [comment]
Fonctionnalité implémentée donc closed! 🍾
