### ISSUE TITLE
Ajouter un fil d'actualité dans la section des nouvelles

### ISSUE THREAD

**Issue by Sonphil** [ApplETS/ETSMobile-Android2#98]
Actuellement, afin de consulter les nouvelles publications, l'utilisateur doit cliquer sur chaque source auquelle il s'est abonnée. Il serait intéressant d'ajouter un fil d'actualité présentant toutes les publications des sources choisies afin que l'utilisateur puisse consulter rapidement les nouvelles publications.

**Comment by zaclimon** [comment]
Les nouvelles sont retirées pour le moment dans cette version d'ÉTSMobile. Ils pourraient être considérés pour la nouvelle version:

https://github.com/ApplETS/Notre-Dame
